# Guide
# https://swagger.io/docs/specification/basic-structure/


swagger: '2.0'
info:
  title: Casefile Management API
  description: A Casefile management API which tracks, and records the tasks, history, and comments that are associated with the case.
  version: 1.0
  contact: 
    email: 'talktous@sholiaslp.com'
  license:
    name: Apache 2.0
    url: 'http://apache.org'
  servers:
    -url: 'http://localhost:3000'
    description: This is my local server
    -url: 'http://company:3000'
    description: This is my development server

schemes: [http, https]



paths:
  /api/v1/: 
    get:
      tags:
        - Default
      summary: Health Check
      description: This is the API's root route. Returns an object when the server has started
      responses:
        200:
          description: Success
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status: 
                    type: object
                    properties:
                      code: 
                        type: number
                      message:
                        type: string
                  message: 
                    type: string