components:
  parameters:
    CasefileID:
      in: path
      name: id
      description: Casefile ID
      required: true
      schema: 
        type: integer

    TransactionID:
      in: path
      name: id
      description: Casefile ID
      required: true
      schema: 
        type: integer



